language: go

sudo: false

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libpcap-dev

script:
  - go test -v -race $(go list ./...)
  - cd examples/packetparser && go build && ./packetparser -h
